### ISSUE TITLE
Manage TaskType

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#10]
## Expected behaviour
We want to be able to use a CRUD on `TaskType` objects.

## Current behavior
Actually we have no calls on the API
We do not have models too

## Potential solution
 - Create models
 - Create views (calls of the API)
 - Create a serializer for admin like : `AdminTaskTypeSerializer`

**1 - Create new TaskType :**
 - URL : `POST tasktypes/`
 - Restricted to `admin` only
 - params POST : `name`
 - return : the new tasktype serialization

**2 - Delete a tasktype :**
 - URL : `DELETE tasktypes/$id`
 - Restricted to `admin` only
 - params POST : no one
 - return : nothing

**3 - Update a tasktype :**
 - URL : `PATCH tasktypes/$id`
 - Restricted to `admin` only
 - params POST : `name`
 - return : the tasktype serialization (complete)

**4 - List tasktypes :**
 - URL : `GET tasktypes/`
 - Restricted to `admin` only
 - return : a list of all tasktypes serialization

**5 - Detail of a tasktype :**
 - URL : `GET tasktypes/$id`
 - Restricted to `admin` only
 - return : the tasktype serialization

**Comment by DarkFranX** [comment]
#35
