### ISSUE TITLE
Revise custom error messages

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/API-Volontaria#103]
## Expected behaviour
API error messages should be as standard as possible. Consequently, generic error messages should NOT be custom. Generic error messages should come directly from standard DRF's error messages.

## Current behavior
Some custom error messages are generic. That means that useless translations are needed. Standard DRF's error messages are already translated in major languages.

## Potential solution
Find a way to replace custom error messages by those originating directly from DRF's system.

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/10
