### ISSUE TITLE
Translate custom error messages

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/API-Volontaria#104]
## Expected behaviour
When I use the API in french language, I expect to receive all error messages in french.

## Current behavior
Translation system is in place, but custom error messages are not translated yet!

## Potential solution
Update .po files for every app

**Comment by RignonNoel** [comment]
I've configured a `transifex` account to manage translation in team :

https://www.transifex.com/fjnr/api-volontaria/dashboard/

When all translations will be reviewed we will be able to merge these files in our github :)

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/9
