### ISSUE TITLE
Add pycodestyle to requirement

### ISSUE THREAD

**Issue by DarkFranX** [Volontaria/API-Volontaria#13]
## Expected behaviour
 I expect to have all needed packages for dev by installing requirement file's content

## Current behavior
 pip requirement file does not contain pep8 (deprecated) nor pycodestyle

## Potential solution
 Add `pycodestyle` to pip requirements.
 Otherwise we'll need an easy solution for developers.

Also, Travis is using pep8. Shouldn't it be using pycodestyle?
ref: 
https://github.com/PyCQA/pycodestyle/issues/572
https://github.com/PyCQA/pycodestyle/issues/466

**Comment by RignonNoel** [comment]
Oh! That's a good information!

I propose to create a `dev-requirements.txt` who contains all dev dependencies. If we do that, new contributor can easily setup all requirements with two command of pip (one for general requirements, one for dev requirements)

And yes we need to change all `pep8` usage (only `travis` for the moment) by `pycodestyle`

**Comment by DarkFranX** [comment]
Closed with PR #19
