### ISSUE TITLE
When entering events dates outside the range of the cycle dates, we get an error

### ISSUE THREAD

**Issue by yanicolivier** [Volontaria/API-Volontaria#149]
## Expected behaviour
We should have an error message in admin event panel saying that the date must be inside the cycle dates.

## Current behavior
500

## Potential solution
Add a custom validation

## Step to reproduce (if it's a bug)

1. Create a cycle
2. Create an event with dates is outside the cycle date
3. Save
4. 500

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/6
