### ISSUE TITLE
Would be nice to have a report of all the volunteer with compiled time exportable to a file

### ISSUE THREAD

**Issue by yanicolivier** [Volontaria/API-Volontaria#154]
## Expected behaviour
Need to have a report of all the compiled time per volunteer

## Current behavior
No options

## Potential solution
Must add [this](https://github.com/Volontaria/API-Volontaria/issues/152) first and add a tool to generate the report

**Comment by RignonNoel** [comment]
What's the difference with issue #147 ?

**Comment by yanicolivier** [comment]
This report will give a list of unique User with their compiled time.  The issue #147 is only is just a plain exportation of the Participation model based on the filter.  I have the solution for both of the issues, just need time to make the clean PR ;)

**Comment by RignonNoel** [comment]
Ok, i understand. Thanks for the explanation
