### ISSUE TITLE
Manage users

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#20]
## Expected behaviour
We want to be able to : 
 - signup
 - activate our account 
 - get information about a given user
 - list users

## Current behavior
Actually we have no calls on the API
We do not have models too

## Potential solution
 - Create models
 - Create views (calls of the API)
 - Create a serializer for basic user like : `BasicUserSerializer`

**1 - Create new user :**
 - URL : `POST users/`
 - No authentication required
 - params POST : `username`, `email`, `password`
 - return : the new user serialization

`User.is_active = False` at this step of the creation
Un email de bienvenue est envoye au user afin de valider son inscription (https://www.sendinblue.com)

**2 - Detail of a user :**
 - URL : `GET users/$id`
 - Restricted to `admin` only
 - return : the user serialization

**3 - Activate a user :**
 - URL : `POST users/`
 - No authentication required
 - params POST : `activation-token`
 - return : the new user serialization

**4 - List all user :**
 - URL : `GET users/`
 - Restricted to `admin` only
 - return : the user serialization

**Comment by willkoua** [comment]
i take this issue

**Comment by RignonNoel** [comment]
No problem @willkoua, we will let you a week to check this issue :)
You can take a look on PR #27 that is a similar functionnality.

Do not hesitate to contact us on the slack server if you need some help!

**Comment by willkoua** [comment]
delete , update, list done
create done but, i find how replace username by email

**Comment by RignonNoel** [comment]
@willkoua Can't you just overwrite the `save()` method of the model to put `username` equal to the `email` field if you don't have value for the `username` field ?
