### ISSUE TITLE
Travis coding style check

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/API-Volontaria#22]
## Expected behaviour
Travis should be checking the coding style too, ie: ending comma in a list or dict

## Current behavior
Travis is currently checking syntax according to the PEP8 styleguide.

## Potential solution
We should make a personalized style check in Travis' file
- Use the [flake8-commas](https://github.com/flake8-commas/flake8-commas) module to lint trailing commas.
- Refer to this [blog post](https://ironboundsoftware.com/blog/2016/12/05/improving-your-python-pylint-and-flake8-emacs/) where flake8 and pylint are used together.

**Comment by RignonNoel** [comment]
I took some time to read about python linter and i've understand that flake8 is an enhancement of `pycodestyle` we use actually by the fact it add some other features.

**Here a citation of the official documentation :**
> ```
> Flake8 is a wrapper around these tools:
> 
>     PyFlakes
>     pycodestyle
>     Ned Batchelder’s McCabe script
> ```
> https://pypi.python.org/pypi/flake8

**Here a big scope description made on StackOverFlow :**
> There are several lint-type programs for Python:   
>  - pyflakes - parses, great for finding NameErrors, obsolete imports 
> - pylint - parses, very comprehensive (on the excessive-compulsive side). 
> - pep8 - parses, a style checker. 
> - flake8 - parser, combines pep8 and pyflakes, with added complexity support, extensible. 
> - pychecker - executes (be careful)   
> All have helped me find small issues and have their pros and cons.  There is also a lot of discussion > here.
> https://stackoverflow.com/questions/5611776/what-are-the-comprehensive-lint-checkers-for-python#7925369

Flake8 authorized to add your own config file but i've not really found the possibility to add complexe rule like "check if we have a coma on the last line of an iteration". I will try to continue my research when i will have some time.

**Comment by DarkFranX** [comment]
I suggest checking out `pylint` in more depth. 

Check out this [blog post](https://ironboundsoftware.com/blog/2016/12/05/improving-your-python-pylint-and-flake8-emacs/) where flake8 and pylint are used together.

**Comment by RignonNoel** [comment]
@DarkFranX I agree! The [link in it](https://codewithoutrules.com/2016/10/19/pylint/) is very helpful and i think it's what we want!

If `pylint` doesn't give us some options we want, maybe it's not a good options in Python.

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/21
