### ISSUE TITLE
Add default email template

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#246]
## Introduction

We want to keep Volontaria easy to install in order to not scare new organizations willing to use this project. 

In this context, we need to enhance our system of emails to send default email by default and stop requiring customs templates for each of the instances we install. 

This request was made by an organization already using the project: https://feathub.com/Volontaria/API-Volontaria/+7

Feel free to help us keep Volontaria easy to install for the new organizations and new contributors!

## Expected behavior

 - If we install a new instance we should just have to specify a SendinBlue API key and it should run automatically with the default template from Volontaria.
 - If the administrator of an instance want to configure an extern template for Email we should let it do it

## Current behavior
We need to create our own custom template on our Sendinblue account

## Potential solution

1. Create a default template in HTML/CSS directly in the code
2. Detect if a template ID has been described in the settings or envvar
3. if no template ID has been described, sent the default Volontaria template as an HTMl message with the SendinBlue API key of the instance

**Comment by Vardane** [comment]
Started working on this issue.
