### ISSUE TITLE
Allowing management of position inside organization

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#254]
## Introduction

Volontaria is used by organizations to help find new volunteers on specifics event, however, some organizations need to do some recurring tasks like accounting or intern management and can have difficulties finding volunteers to do these tasks.

We want to help organizations finding new volunteers to fill some positions inside the organization.

## Expected behavior

 - An administrator can create one or multiple positions
 - A user can apply on positions
 - An administrator can see the applications
 - An administrator can fill a position with one of the applicants

## Current behavior

There is no system for positions, only specific events can be described in Volontaria.

## Potential solution

1. Create a new Django app `Position` to group these new features
2. Create a new `Position` model (name, description, hourly wage, number of hours per week, the minimum duration of engagement, remote job or not, boolean to know if the position is visible or not)
3. Create a new `Application` model (ForeignKey to the applicant User, creation date, TextField to let the user write a little motivation message or describe some important point to the organization, boolean to know if the application is winning or not / if the user is enroll or not)
4. Create serializer and view to make sure:
  - the administrators can create new positions
  - the administrator can edit a position
  - the users can list positions
  - the users can apply to an existing position
  - the administrator can select which application they want to enroll for a specific position

**Comment by Vardane** [comment]
Started working on it as part of September 2020 Montreal Python hackathon
