### ISSUE TITLE
Feature to import/create new events from CSV

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#255]
## Introduction

Some organizations create a lot of events sometimes and it can be really painful to create each event one by one with a form. We want to help these organizations easily create a group of events in a limited time by just importing a CSV file with all the data in it.

Organizations will be able to manage their events with Excel, OpenOffice, LibreOffice or Google Spreadsheet without technical knowledge and just drag and drop it into Volontaria.

Feel free to help us keep Volontaria easy and powerful for the organization by contributing on this issue.

## Expected behavior

 - The administrators can create multiple events by providing a CSV
 - If the format fail, the import is forbidden and no changes have been made to the file or the DB
 - If the format fail, an error describing the problem is returned to the administrator to help him fix it and retry
 - If the format of the file is good, all the events are created

## Current behavior

Administrator need to create each event manually with a HTTP POST request

## Potential solution

1. Modify the `Event` view to allow creating event from a CSV file
2. You can use `transaction.atomic()` (`from django.db import transaction`) to avoid change on the DB in case of fail on a row
3. Optional: You can ask for an optional dict that help you match some column of the CSV to your data and allow administrator to import multiple format of file

**Comment by RignonNoel** [comment]
On the CSV reading part, we will need a `parser` (ie: a tool to read and extract data from the CSV and transform it into another format). This could be done by a custom python `class` that we will be able to integrate into Django after.

This class can for example get a file in input and give us some methods to:

 - Know the name of the columns available in the file
 - Validate the format of the file (and return some errors if needed)
 - Transform the content of the file into JSON

To begin this class can accept CSV only, and be enhance after that to accept other types of file like Excel

Helping links:

1. [Reading and writing CSV files](https://realpython.com/python-csv/)

**Comment by sylvaus** [comment]
I would like to work on this task
