### ISSUE TITLE
Form to update user password from admin panel

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#269]
## Expected behavior
Administrator can change password of user directly from Django admin panel

## Current behavior
The Django admin panel just show the hashed password in database and do not offer an easy form to update the value.

## Potential solution
> How to fix the bug or how to make an improvement on the current product.

## Step to reproduce (if it's a bug)

1. Go to Django admin
2. Go to the User section
3. Click on a user to open it
4. You should see the missing form

![Screenshot_2020-12-14 Change user Django site admin](https://user-images.githubusercontent.com/12053720/102144412-714c1d80-3e33-11eb-9414-eebec23fb4f3.png)

## Your environment (if it's a bugs)

* Version used : 2.0.0

**Comment by yanicolivier** [comment]
I'm working on this !
