### ISSUE TITLE
Overwriting of settings.py

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#270]
## Expected behavior
Technician should be able to use an overwrite of our `settings.py` to add his own config if needed. (The `ENV` var that we create can miss some settings he need).

## Current behavior
The documentation say that it's possible but in fact we do not have this feature since the V2.0.0

## Potential solution
1. We need to import a `local_settings.py` as specified in the documentation and give an example file for new technician.
2. The example file should contain a comment that explain to technicians that we also support usage of `ENV` var
3. A link to the documentation should be available in the comment

Here is the actual documentation:
![Screenshot_2020-12-14 Install manually - Plateforme Volontaria](https://user-images.githubusercontent.com/12053720/102145164-c2a8dc80-3e34-11eb-8a32-5df2e82aaf75.png)

## Step to reproduce (if it's a bug)

1. Create a `local_settings.py` with some custom settings
2. Run your website
3. Nothing changed

## Your environment (if it's a bugs)

* Version used : V2.0.0 
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): Ubuntu 18.04.5 LTS

**Comment by yanicolivier** [comment]
I'll take care of that !
