### ISSUE TITLE
Migrations problem on TemporaryToken

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#28]
## Expected behaviour
We we run `makemigrations` command, we want to have only new modification and not a list of default field who change in function of time and spam the migrations system

## Current behavior
Actually, when we run the `makemigrations` command we have **ALWAYS** a new migrations from the`TemporaryToken` model.

## Potential solution
Change the way we put the `default` value to not change each time we create a new migration.

A potential solution (maybe not the best, i don't know) is to overwrite the `save()` method of the model class to change the default value. This way we migrations system will be not impacted.

```python
class TemporaryToken(Token):
    """Subclass of Token to add an expiration time."""
    expires = models.DateTimeField(
        default=timezone.now() + timezone.timedelta(
            minutes=settings.REST_FRAMEWORK_TEMPORARY_TOKENS['MINUTES']
        )
)
```
## Step to reproduce (if it's a bug)

1. run `python source/apiVolontaria/manage.py makemigrations`
2. check the migration folder of the `apiVolontaria` application.
3. a new migration has been created only to change the default value with new value of time

## Your environment (if it's a bugs)

* Version used : Develop version
* Version of softwares (python, firefox, chrome, ..) : Python 3.6.2
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): ArchLinux

**Comment by DarkFranX** [comment]
closed by #29
