### ISSUE TITLE
Add  __str__() method to existing models

### ISSUE THREAD

**Issue by DarkFranX** [Volontaria/API-Volontaria#40]
## Expected behaviour
> Models should have a __str__() method to get a meaningful representation on the objects.
```python
>>> TaskType.objects.all()
<QuerySet [<TaskType: tasktype_name>]>
```
## Current behavior
> No __str__() method are defined in the models. That means, for example, that when we query a set of objects of a model in the shell, we get something like 
```python
>>> TaskType.objects.all()
<QuerySet [<TaskType: TaskType object>]>
```

## Potential solution
> The method whould be added (TaskType and Cycle). See the [Django Tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial02/#playing-with-the-api) for more details.

**Comment by RignonNoel** [comment]
Good point, it will be more user friendly on the admin panel side too!

**Comment by DarkFranX** [comment]
Exactly, that is the major benefit!

**Comment by RignonNoel** [comment]
Don't forget to ad test on all `str()` method in some `test_model_....` file :)
