### ISSUE TITLE
Sync of migrations

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#49]
## Expected behaviour
When i make a makemigrations from the develop branch, i've no one change.

## Current behavior
When i make a makemigrations from the develop branch, i've this:
```
Migrations for 'apiVolontaria':
  source/apiVolontaria/apiVolontaria/migrations/0004_auto_20171224_1736.py
    - Alter field created on activationtoken
Migrations for 'location':
  source/apiVolontaria/location/migrations/0002_auto_20171224_1736.py
    - Alter unique_together for country (0 constraint(s))
    - Alter unique_together for stateprovince (0 constraint(s))
```

## Potential solution
1. Make a PR to fix this result
2. Implement a test to check the `makemigrations` doesn't return new migrations file on TravisCI

## Step to reproduce (if it's a bug)

1. Pull the develop branch
2. Call the `makemigrations` command : `python source/apiGiggle/manage.py makemigrations`
3. Check the result

## Your environment (if it's a bugs)

* Version used : Develop (commit : `c2cd8d19ad4e0d196ac22b33fcb2b6b9576adba2`)
* Version of softwares (python, firefox, chrome, ..) : `Python 3.6.3`
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): `Arch Linux`

**Comment by DarkFranX** [comment]
For the `location` app, that happens because I forgot to update the migration files after the changes requested in the reviews of the PR #46. That can be easily fixed!
As for the activationtoken, I am not sure why this happened.
