### ISSUE TITLE
PATCH doesn't use `partial_update()`

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#50]
## Expected behaviour
When i call the API with a HTTP `PATCH` verb i want to make a partial update of the ressource.

## Current behavior
Actually we call the `update()` function of the view and not the `partial_update()` who make only a partial update.

```python
def patch(self, request, *args, **kwargs):
    if self.request.user.has_perm('volunteer.update_cell'):
        return self.update(request, *args, **kwargs)
```
## Potential solution
Change :
```python
return self.update(request, *args, **kwargs)
``` 
to :
```python
return self.partial_update(request, *args, **kwargs)
```

on each view already implemented (`EventsId` is already done)

## Step to reproduce (if it's a bug)

No need to reproduce, just look the code.

## Your environment (if it's a bugs)

* Version used : Develop (commit : `c2cd8d19ad4e0d196ac22b33fcb2b6b9576adba2`)
* Version of softwares (python, firefox, chrome, ..) : No need
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): No need

**Comment by RignonNoel** [comment]
@willkoua Work on it

**Comment by willkoua** [comment]
done
