### ISSUE TITLE
translations of error message

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#72]
## Expected behavior
I want to receive all messages from the API in my preferred language.

## Current behavior
Actually all error message from the API is in English, 

## Potential solution
- Make translation of all error/success message of the API 
- Allow change the language in the settings

**Comment by willkoua** [comment]
i take this task

**Comment by RignonNoel** [comment]
Ok :)

**Comment by francisjeanneau** [comment]
Here is a resource to get you started: http://www.django-rest-framework.org/topics/internationalization
