### ISSUE TITLE
Manage Cell

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#8]
## Expected behaviour
We want to be able to use a CRUD on `Cells` objects.

## Current behavior
Actually we have no calls on the API
We do not have models too

## Potential solution
 - Create models
 - Create views (calls of the API)
 - Create a serializer for admin like : `AdminCellSerializer`

**1 - Create new cell :**
 - URL : `POST cells/`
 - Restricted to `admin` only
 - params POST : `name`
 - return : the new cell serialization

**2 - Delete a cell :**
 - URL : `DELETE cells/$id`
 - Restricted to `admin` only
 - params POST : no one
 - return : nothing

**3 - Update a cell :**
 - URL : `PATCH cells/$id`
 - Restricted to `admin` only
 - params POST : `name`
 - return : the cell serialization (complete)

**4 - List cells :**
 - URL : `GET cells/`
 - Restricted to `admin` only
 - return : a list of all cell serialization

**5 - Detail of a cell :**
 - URL : `GET cells/$id`
 - Restricted to `admin` only
 - return : the cell serialization

**Comment by DarkFranX** [comment]
I think we'd like to store more information related to cells such as the full address. Could we officialize that and modify the DB scheme accordingly?
