### ISSUE TITLE
Auto-generate code's documentation

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/API-Volontaria#82]
## Expected behaviour
We need a way to auto-generate our code's documentation

## Current behavior
No documentation is auto-generated (except the API endpoints with swagger)

## Potential solution
We could use [Sphinx](http://www.sphinx-doc.org/en/stable/) and be able to upload our docs to readthedocs and/or github.

**Comment by RignonNoel** [comment]
Which documentation is particulary important ?
API documentation already give us all Endpoints, Urls and Views are standard. Maybe can we begin with the Model documentation ?

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/13
