### ISSUE TITLE
New system of notification

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#89]
## Expected behaviour
Allow system to give some notification to some users

## Current behavior
We don't have a system of notification

## Potential solution
 - Create a new model `Notification`
 - Update model `Profile` to have some new preferencies (`default=False`)
 - Create a new signals to launch email when a new `Notification` is created
 - Add endpoint `GET notifications/`
 - Add endpoint `GET notifications/:id`

![tp1d2i9038nteknsqxx0xowlboaeqmbjge7vwka4hroxowuanpxlyf9yumifhicktw6oc6fshfdumza90vttdvpooud85tt2vqgu0dgxdim-07fc3dopzr3hi8t1e5yhcmkb8wzdufbx79ljtltmknhxojv67dprnr9lz8uf58xow4xiito_fdhz8mjyn6ora8vd6dxo7hs8wv0remdopan-p0i0](https://user-images.githubusercontent.com/12053720/35340797-257f6924-00f2-11e8-8bda-924cb087460a.png)

```
@startuml

title Notification System - Class Diagram


class Notification {
    +TextField content
    +CharField title
}

class User {
}

class Profile {
    + ...
    +BooleanField send_email
    +BooleanField send_sms
    + ...
}

Notification -> User : notify > 
User -> Profile
@enduml
```

**Comment by willkoua** [comment]
i take this issue

**Comment by willkoua** [comment]
i can't work on this issue now. I have a big feature for my job. so, if someone want take this issue no problem if not i will work on this issue in 1 or 2 week

**Comment by RignonNoel** [comment]
Django anymail 2.0 is now available : https://github.com/anymail/django-anymail/releases/tag/v2.0
Since my contribution has been accepted, we can use it with SendinBlue.

**Comment by RignonNoel** [comment]
Please move here : https://genielibre.com/issues/1
