### ISSUE TITLE
Email unique constraint is case sensitive

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/API-Volontaria#94]
## Expected behaviour
When I sign up, I need to provide a email address. I expect the API to reject the subscription if the email is already associated with an existing user.

## Current behavior
The email unique constraint check is case sensitive, which means that I can subscribe with the same email address if the case of the characters are different. 
Example:
```
User1: {
    email: "test@gmail.com"
}
```
is considered by the API as different from:
```
User2: {
    email: "Test@gmail.com"
}
```

## Potential solution
I see 2 possibilities right now:
- Change the `unique` constraint to be case **insensitive**
- Automatically lowercase() all email address before saving the User instance

## Step to reproduce (if it's a bug)

1. Sign up a user at POST /users
2. Sign up another user at POST /users with the same email, but with a capital first letter
3. Should successfully create second user event if email is duplicated.

## Your environment (if it's a bugs)

* Version used : Latest develop as of January 27th of 2018 @ 15h11
* Version of softwares (python, firefox, chrome, ..) : Python 3.6, Chrome 60
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): ArchLinux

**Comment by RignonNoel** [comment]
I think both solutions are good and can be done in the same time!

Really good check!

**Comment by RignonNoel** [comment]
Apparently email address could be case sensitive in some part :
https://stackoverflow.com/a/9808332

I think we are better to let this behavior that way, people can create a lot of false and free email address if they really want to have multiple account, so make it really unique do not resolve all the problem.

**Comment by RignonNoel** [comment]
I close this issue since it's not valid. Do not hesitate to discuss it and reopen it :)
